### ISSUE TITLE
PlayerController Gravity is broken

### ISSUE THREAD

**Issue by Maroski** [Maroski/VRProject#1]
Gravity is not working properly for the PlayerController (it's possible to move up, but not down)

**Comment by Maroski** [comment]
Kinematic option was enabled on the rigidbody, preventing any forces from working on it. Just make sure IsKinematic is unchecked/false.

**Comment by mprysia** [comment]
While we can enable gravity like that it seems like we may run into problems:
http://answers.unity3d.com/questions/334708/gravity-with-character-controller.html

For now the above commit is the fix that I came up with. I believe we will have to implement gravity and add it to our calculations since we probably want the controller to be kinematic (we quite possibly will have to defy gravity in certain circumstances such as wall jumping etc.)
